-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: NguoiDung (Extends auth.users)
CREATE TABLE IF NOT EXISTS "public"."NguoiDung" (
    "maNguoiDung" UUID PRIMARY KEY REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "email" VARCHAR NOT NULL,
    "hoTen" TEXT NOT NULL,
    "anhDaiDien" TEXT,
    "vaiTro" VARCHAR NOT NULL CHECK ("vaiTro" IN ('tester', 'client', 'admin')),
    "gioiTinh" VARCHAR CHECK ("gioiTinh" IN ('Nam', 'Nữ', 'Khác')),
    "ngaySinh" DATE,
    "diaChi" JSONB,
    "gioiThieu" TEXT,
    "linkLinkedIn" TEXT,
    "ngayTao" TIMESTAMPTZ DEFAULT NOW(),
    "thongTinThanhToan" JSONB,
    CONSTRAINT "NguoiDung_email_key" UNIQUE ("email")
);

-- Table: HoSoTester
CREATE TABLE IF NOT EXISTS "public"."HoSoTester" (
    "maNguoiDung" UUID PRIMARY KEY REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "soNamKinhNghiem" INTEGER NOT NULL,
    "ngonNguChinh" TEXT,
    "ngonNguKhac" JSONB,
    "thongTinThietBi" JSONB,
    "thongTinKiemThu" JSONB
);

-- Table: HoSoClient
CREATE TABLE IF NOT EXISTS "public"."HoSoClient" (
    "maNguoiDung" UUID PRIMARY KEY REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "tenCongTy" TEXT NOT NULL,
    "maSoThue" TEXT NOT NULL,
    "website" TEXT NOT NULL,
    "quyMoCongTy" VARCHAR NOT NULL,
    "linhVucHoatDong" TEXT NOT NULL,
    "viTriCongViec" TEXT NOT NULL
);

-- Table: DuAn
CREATE TABLE IF NOT EXISTS "public"."DuAn" (
    "maDuAn" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maNguoiTao" UUID NOT NULL REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "maDuAnHienThi" TEXT NOT NULL,
    "tieuDe" TEXT,
    "moTa" TEXT,
    "loaiDuAn" TEXT NOT NULL,
    "cauHoiKhaoSat" JSONB,
    "nganSach" DECIMAL NOT NULL,
    "yeuCauMoiTruong" JSONB,
    "phamViTest" JSONB,
    "huongDanTruyCap" TEXT,
    "huongDanKyThuat" TEXT,
    "taiLieuDinhKem" JSONB,
    "cauHinhThanhToan" JSONB,
    "soLuongCanTuyen" INTEGER NOT NULL DEFAULT 10,
    "thoiHanNopBai" TIMESTAMPTZ,
    "thoiHanDuAn" TIMESTAMPTZ,
    "trangThaiDuAn" VARCHAR NOT NULL DEFAULT 'Chờ duyệt' CHECK ("trangThaiDuAn" IN ('Chờ duyệt', 'Đang mở', 'Đóng', 'Bị từ chối')),
    "ngayTao" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table: UngTuyen
CREATE TABLE IF NOT EXISTS "public"."UngTuyen" (
    "maUngTuyen" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maDuAn" BIGINT NOT NULL REFERENCES "public"."DuAn"("maDuAn") ON DELETE CASCADE,
    "maUngVien" UUID NOT NULL REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "traLoiKhaoSat" JSONB,
    "trangThaiUngTuyen" VARCHAR NOT NULL CHECK ("trangThaiUngTuyen" IN ('Chờ duyệt', 'Chấp nhận', 'Từ chối')),
    "ngayUngTuyen" TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT "unique_UngTuyen" UNIQUE ("maDuAn", "maUngVien")
);

-- Table: KichBanKiemThu
CREATE TABLE IF NOT EXISTS "public"."KichBanKiemThu" (
    "maKichBan" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maDuAn" BIGINT NOT NULL REFERENCES "public"."DuAn"("maDuAn") ON DELETE CASCADE,
    "maKichBanHienThi" VARCHAR NOT NULL,
    "tieuDe" TEXT NOT NULL,
    "dieuKienTienQuyet" TEXT,
    "huongDanDacBiet" JSONB,
    "cacBuocThucHien" JSONB NOT NULL,
    "cauHoiBoSung" JSONB NOT NULL,
    "yeuCauBangChung" VARCHAR DEFAULT NULL,
    "ngayTao" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table: KetQuaKiemThu
CREATE TABLE IF NOT EXISTS "public"."KetQuaKiemThu" (
    "maKetQua" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maKichBan" BIGINT NOT NULL REFERENCES "public"."KichBanKiemThu"("maKichBan") ON DELETE CASCADE,
    "maNguoiThucHien" UUID NOT NULL REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "thietBiSuDung" JSONB,
    "ketQuaTungBuoc" JSONB,
    "trangThaiChung" VARCHAR CHECK ("trangThaiChung" IN ('Pass', 'Fail', 'Blocked', 'Skip')),
    "ketQuaThucTeChung" TEXT,
    "maBaoCaoLoiLienQuan" VARCHAR,
    "lyDoBiChan" TEXT,
    "lyDoBoQua" TEXT,
    "thongTinBoSung" JSONB,
    "fileBangChung" JSONB,
    "trangThaiDuyet" VARCHAR DEFAULT 'Chờ duyệt' CHECK ("trangThaiDuyet" IN ('Chờ duyệt', 'Đã duyệt', 'Từ chối', 'Yêu cầu chỉnh sửa')),
    "phanHoiCuaClient" JSONB,
    "ngayThucHien" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: BaoCaoLoi
CREATE TABLE IF NOT EXISTS "public"."BaoCaoLoi" (
    "maLoi" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maDuAn" BIGINT NOT NULL REFERENCES "public"."DuAn"("maDuAn") ON DELETE CASCADE,
    "maNguoiBaoCao" UUID NOT NULL REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE CASCADE,
    "maKetQuaKiemThu" BIGINT REFERENCES "public"."KetQuaKiemThu"("maKetQua") ON DELETE SET NULL,
    "maLoiHienThi" VARCHAR NOT NULL UNIQUE,
    "tieuDe" TEXT NOT NULL,
    "cacBuocTaiHien" JSONB,
    "ketQuaThucTe" TEXT NOT NULL,
    "ketQuaMongDoi" TEXT NOT NULL,
    "mucDoNghiemTrong" VARCHAR CHECK ("mucDoNghiemTrong" IN ('Nguy cấp', 'Cao', 'Trung bình', 'Thấp')),
    "khaNangTaiTao" VARCHAR,
    "fileBangChung" JSONB,
    "thongTinTrinhDuyet" JSONB,
    "trangThaiLoi" VARCHAR CHECK ("trangThaiLoi" IN ('Đang xử lý', 'Đã duyệt', 'Từ chối', 'Đã chỉnh sửa và Chấp nhận')),
    "phanHoiCuaClient" TEXT,
    "ngayBaoCao" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: KenhChat
CREATE TABLE IF NOT EXISTS "public"."KenhChat" (
    "maKenh" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maDuAn" BIGINT REFERENCES "public"."DuAn"("maDuAn") ON DELETE CASCADE,
    "tenKenh" TEXT,
    "loaiKenh" VARCHAR
);

-- Table: TinNhan
CREATE TABLE IF NOT EXISTS "public"."TinNhan" (
    "maTinNhan" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maKenh" BIGINT REFERENCES "public"."KenhChat"("maKenh") ON DELETE CASCADE,
    "maNguoiGui" UUID REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE SET NULL,
    "noiDung" TEXT,
    "fileDinhKem" TEXT,
    "thoiGianGui" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: ThanhToan
CREATE TABLE IF NOT EXISTS "public"."ThanhToan" (
    "maGiaoDich" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maDuAn" BIGINT REFERENCES "public"."DuAn"("maDuAn") ON DELETE SET NULL,
    "maNguoiNhan" UUID REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE SET NULL,
    "soTien" DECIMAL,
    "moTaGiaoDich" TEXT,
    "trangThaiThanhToan" VARCHAR,
    "ngayGiaoDich" TIMESTAMPTZ DEFAULT NOW()
);

-- Table: HoTro
CREATE TABLE IF NOT EXISTS "public"."HoTro" (
    "maYeuCau" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "maNguoiGui" UUID REFERENCES "public"."NguoiDung"("maNguoiDung") ON DELETE SET NULL,
    "tieuDe" TEXT,
    "noiDung" TEXT,
    "fileDinhKem" JSONB,
    "trangThaiHoTro" VARCHAR,
    "phanHoiAdmin" TEXT,
    "ngayGui" TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS "idx_NguoiDung_email" ON "public"."NguoiDung"("email");
CREATE INDEX IF NOT EXISTS "idx_DuAn_maNguoiTao" ON "public"."DuAn"("maNguoiTao");
CREATE INDEX IF NOT EXISTS "idx_UngTuyen_maDuAn" ON "public"."UngTuyen"("maDuAn");
CREATE INDEX IF NOT EXISTS "idx_UngTuyen_maUngVien" ON "public"."UngTuyen"("maUngVien");
CREATE INDEX IF NOT EXISTS "idx_BaoCaoLoi_maDuAn" ON "public"."BaoCaoLoi"("maDuAn");
CREATE INDEX IF NOT EXISTS "idx_BaoCaoLoi_maNguoiBaoCao" ON "public"."BaoCaoLoi"("maNguoiBaoCao");
CREATE INDEX IF NOT EXISTS "idx_TinNhan_maKenh" ON "public"."TinNhan"("maKenh");

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE "public"."NguoiDung" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."HoSoTester" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."HoSoClient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."DuAn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."UngTuyen" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."KichBanKiemThu" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."KetQuaKiemThu" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."BaoCaoLoi" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."KenhChat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."TinNhan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ThanhToan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."HoTro" ENABLE ROW LEVEL SECURITY;

-- Create basic policies (can be refined later)
-- NguoiDung: Users can read their own profile.
CREATE POLICY "Users can read own profile" ON "public"."NguoiDung"
    FOR SELECT USING (auth.uid() = "maNguoiDung");

CREATE POLICY "Users can update own profile" ON "public"."NguoiDung"
    FOR UPDATE USING (auth.uid() = "maNguoiDung");

-- Allow inserting into NguoiDung during registration (trigger or direct insert)
-- For now, allow authenticated users to insert their own row
CREATE POLICY "Users can insert own profile" ON "public"."NguoiDung"
    FOR INSERT WITH CHECK (auth.uid() = "maNguoiDung");

-- Public read access for some tables might be needed later, but starting strict.
